<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{852e9656-65ce-4dc2-8fb3-58084af07b1c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR	
END_VAR
VAR CONSTANT
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Only enable one example at a time. 
//-----------------------------------

POU_Example2PositionalMoves();
//POU_ExampleDynamicMoves();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="169" Count="0" />
      <LineId Id="171" Count="0" />
      <LineId Id="170" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="168" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>